import { User, Incident, Resource, Hospital, Dispatch } from '../src/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-001',
    name: 'Inspector Vikram Rathore',
    email: 'operator@resqra.gov.in',
    role: 'OPERATOR',
    badgeNumber: 'OP-4082',
    agency: 'State Emergency Operations Center (SEOC)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-002',
    name: 'Capt. Ananya Sharma',
    email: 'admin@resqra.gov.in',
    role: 'ADMIN',
    badgeNumber: 'DIR-001',
    agency: 'Disaster Management Authority',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-003',
    name: 'Dr. Arjun Verma',
    email: 'responder1@resqra.gov.in',
    role: 'RESPONDER',
    badgeNumber: 'MED-12',
    agency: 'Rapid Emergency Medical Team #04',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-004',
    name: 'Sgt. Rajesh Kumar',
    email: 'responder2@resqra.gov.in',
    role: 'RESPONDER',
    badgeNumber: 'NDRF-BOAT-02',
    agency: 'NDRF Water Rescue Squad',
  },
  {
    id: 'usr-005',
    name: 'Aditya Srivastava',
    email: 'citizen@resqra.gov.in',
    role: 'CITIZEN',
    agency: 'Resident — Gomti Nagar Extension',
  },
  {
    id: 'usr-006',
    name: 'Priya Mehra',
    email: 'priya@citizen.in',
    role: 'CITIZEN',
  },
  {
    id: 'usr-007',
    name: 'Chief Officer R. K. Singhal',
    email: 'firechief@resqra.gov.in',
    role: 'OPERATOR',
    badgeNumber: 'FIRE-CMD-01',
    agency: 'Lucknow Fire & Rescue Services',
  },
  {
    id: 'usr-008',
    name: 'Paramedic Neha Tripathi',
    email: 'paramedic@resqra.gov.in',
    role: 'RESPONDER',
    badgeNumber: 'AMB-04',
    agency: 'ALS Ambulance Corps',
  },
  {
    id: 'usr-009',
    name: 'Sub-Inspector Rohit Yadav',
    email: 'police@resqra.gov.in',
    role: 'RESPONDER',
    badgeNumber: 'PCR-09',
    agency: 'Lucknow City Police Patrol',
  },
  {
    id: 'usr-010',
    name: 'Dr. Sunita Kulkarni',
    email: 'trauma.lead@resqra.gov.in',
    role: 'OPERATOR',
    badgeNumber: 'KGMU-CHIEF',
    agency: 'KGMU Trauma Coordination',
  },
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-01',
    name: 'KGMU Trauma Center (King George)',
    address: 'Shah Mina Rd, Chowk, Lucknow',
    latitude: 26.8688,
    longitude: 80.9142,
    emergency_beds: 45,
    icu_beds: 24,
    occupied_emergency_beds: 31,
    occupied_icu_beds: 19,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['Level-1 Trauma', 'Neurosurgery', 'Severe Burns', 'Pediatric ICU', 'Blood Bank'],
    has_helipad: true,
    has_blood_bank: true,
    contact_number: '+91-522-2257540',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-02',
    name: 'SGPGI Super Specialty Hospital',
    address: 'Raebareli Rd, Lucknow',
    latitude: 26.7456,
    longitude: 80.9389,
    emergency_beds: 35,
    icu_beds: 28,
    occupied_emergency_beds: 22,
    occupied_icu_beds: 24,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['Advanced Critical Care', 'Cardiovascular Trauma', 'Organ Support', 'Toxicology'],
    has_helipad: true,
    has_blood_bank: true,
    contact_number: '+91-522-2668004',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-03',
    name: 'Dr. Ram Manohar Lohia Institute (RMLIMS)',
    address: 'Vibhuti Khand, Gomti Nagar, Lucknow',
    latitude: 26.8624,
    longitude: 81.0028,
    emergency_beds: 28,
    icu_beds: 16,
    occupied_emergency_beds: 16,
    occupied_icu_beds: 10,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['Emergency Medicine', 'Multi-Trauma', 'Orthopedics', 'Dialysis'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-6692000',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-04',
    name: 'Sahara Hospital Gomti Nagar',
    address: 'Viraj Khand-1, Gomti Nagar, Lucknow',
    latitude: 26.8529,
    longitude: 81.0112,
    emergency_beds: 20,
    icu_beds: 12,
    occupied_emergency_beds: 8,
    occupied_icu_beds: 6,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['Cardiac Emergency', 'Surgical ICU', 'Neuro Trauma'],
    has_helipad: true,
    has_blood_bank: true,
    contact_number: '+91-522-6780001',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-05',
    name: 'Apollo Medics Super Speciality Hospital',
    address: 'Sector B, LDA Colony, Kanpur Rd, Lucknow',
    latitude: 26.7915,
    longitude: 80.8924,
    emergency_beds: 25,
    icu_beds: 15,
    occupied_emergency_beds: 11,
    occupied_icu_beds: 9,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['24/7 Trauma Care', 'Interventional Cardiology', 'Polytrauma'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-6788888',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-06',
    name: 'Civil Hospital (Shyama Prasad Mukherjee)',
    address: 'Park Road, Hazratganj, Lucknow',
    latitude: 26.8488,
    longitude: 80.9465,
    emergency_beds: 22,
    icu_beds: 8,
    occupied_emergency_beds: 18,
    occupied_icu_beds: 7,
    trauma_level: 'LEVEL_2',
    status: 'BUSY',
    specialties: ['Emergency Casualty', 'General Surgery', 'Orthopedic Trauma'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-2239086',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-07',
    name: 'Balrampur District Hospital',
    address: 'Golaganj, Kaiserbagh, Lucknow',
    latitude: 26.8582,
    longitude: 80.9238,
    emergency_beds: 24,
    icu_beds: 10,
    occupied_emergency_beds: 20,
    occupied_icu_beds: 9,
    trauma_level: 'LEVEL_2',
    status: 'BUSY',
    specialties: ['General Trauma', 'Burn Ward', 'Infectious Disease Triage'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-2222204',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-08',
    name: 'Command Hospital Central Command (Military)',
    address: 'Cantonment, Lucknow',
    latitude: 26.8214,
    longitude: 80.9572,
    emergency_beds: 30,
    icu_beds: 18,
    occupied_emergency_beds: 14,
    occupied_icu_beds: 8,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['Military Combat Trauma', 'Blast Injuries', 'Aeromedical Triage'],
    has_helipad: true,
    has_blood_bank: true,
    contact_number: '+91-522-2481020',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-09',
    name: 'Chandan Hospital',
    address: 'Faizabad Rd, Vijayant Khand, Gomti Nagar, Lucknow',
    latitude: 26.8798,
    longitude: 81.0182,
    emergency_beds: 18,
    icu_beds: 10,
    occupied_emergency_beds: 7,
    occupied_icu_beds: 5,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['Advanced Emergency', 'Critical Care', 'Internal Medicine'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-6677777',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-10',
    name: 'Medanta Super Specialty Hospital',
    address: 'Sector A, Pocket 1, Sushant Golf City, Amar Shaheed Path, Lucknow',
    latitude: 26.7725,
    longitude: 80.9982,
    emergency_beds: 40,
    icu_beds: 22,
    occupied_emergency_beds: 19,
    occupied_icu_beds: 12,
    trauma_level: 'LEVEL_1',
    status: 'OPEN',
    specialties: ['Cardiac ICU', 'Comprehensive Polytrauma', 'Neurosciences', 'Pediatric ICU'],
    has_helipad: true,
    has_blood_bank: true,
    contact_number: '+91-522-4505050',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-11',
    name: 'Charak Hospital & Research Centre',
    address: 'Hardoi Road, Dubagga, Lucknow',
    latitude: 26.8724,
    longitude: 80.8524,
    emergency_beds: 16,
    icu_beds: 8,
    occupied_emergency_beds: 14,
    occupied_icu_beds: 7,
    trauma_level: 'LEVEL_3',
    status: 'BUSY',
    specialties: ['Emergency Trauma', 'General Medicine', 'Maternity Emergency'],
    has_helipad: false,
    has_blood_bank: false,
    contact_number: '+91-522-2771234',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-12',
    name: 'Era University Hospital & Trauma Unit',
    address: 'Sarfarazganj, Hardoi Road, Lucknow',
    latitude: 26.8834,
    longitude: 80.8841,
    emergency_beds: 22,
    icu_beds: 12,
    occupied_emergency_beds: 12,
    occupied_icu_beds: 6,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['Accident & Emergency', 'Orthopedic Surgery', 'Blood Storage'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-6604100',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-13',
    name: 'Lok Bandhu Shri Raj Narain Combined Hospital',
    address: 'Sector E, Kanpur Rd, Hind Nagar, Lucknow',
    latitude: 26.7992,
    longitude: 80.9012,
    emergency_beds: 20,
    icu_beds: 6,
    occupied_emergency_beds: 19,
    occupied_icu_beds: 6,
    trauma_level: 'LEVEL_3',
    status: 'FULL',
    specialties: ['Emergency Care', 'Obstetrics', 'Minor Trauma'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-2435555',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-14',
    name: 'Avadh Hospital & Heart Centre',
    address: 'Singar Nagar, Alambagh, Lucknow',
    latitude: 26.8152,
    longitude: 80.9068,
    emergency_beds: 14,
    icu_beds: 6,
    occupied_emergency_beds: 6,
    occupied_icu_beds: 3,
    trauma_level: 'LEVEL_3',
    status: 'OPEN',
    specialties: ['Cardiac Resuscitation', 'Accident Care', 'ICU'],
    has_helipad: false,
    has_blood_bank: false,
    contact_number: '+91-522-2458899',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-15',
    name: 'Mayo Institute of Medical Sciences (Emergency)',
    address: 'Vikas Nagar / Gadia, Lucknow-Faizabad Rd',
    latitude: 26.9015,
    longitude: 81.0412,
    emergency_beds: 24,
    icu_beds: 10,
    occupied_emergency_beds: 15,
    occupied_icu_beds: 7,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['Emergency Medicine', 'Pediatrics', 'Burn Unit'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-2890000',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-16',
    name: 'Mahanagar Maternity & Trauma Center',
    address: 'Mahanagar Extension, Lucknow',
    latitude: 26.8789,
    longitude: 80.9521,
    emergency_beds: 12,
    icu_beds: 4,
    occupied_emergency_beds: 5,
    occupied_icu_beds: 2,
    trauma_level: 'LEVEL_3',
    status: 'OPEN',
    specialties: ['Urgent Care', 'Pediatric Emergency', 'First Line Triage'],
    has_helipad: false,
    has_blood_bank: false,
    contact_number: '+91-522-2331122',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-17',
    name: 'Tender Palm Super Speciality Hospital',
    address: 'Amar Shaheed Path, Golf City, Sector 7, Lucknow',
    latitude: 26.7845,
    longitude: 81.0064,
    emergency_beds: 18,
    icu_beds: 10,
    occupied_emergency_beds: 9,
    occupied_icu_beds: 4,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['24x7 Critical Care', 'Trauma Surgery', 'Organ Support'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-3500000',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-18',
    name: 'Vivekananda Polyclinic & Institute of Medical Sciences',
    address: 'Vivekananda Puram, Nirala Nagar, Lucknow',
    latitude: 26.8741,
    longitude: 80.9392,
    emergency_beds: 26,
    icu_beds: 14,
    occupied_emergency_beds: 17,
    occupied_icu_beds: 11,
    trauma_level: 'LEVEL_2',
    status: 'OPEN',
    specialties: ['Emergency Trauma', 'ICU Care', 'Dialysis', 'Blood Bank'],
    has_helipad: false,
    has_blood_bank: true,
    contact_number: '+91-522-2787720',
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_RESOURCES: Resource[] = [
  // 12 Ambulances (Advanced Life Support & Basic)
  {
    id: 'res-amb-01',
    callsign: 'ALS-MEDIC-01',
    name: 'ALS Ambulance Unit #01',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8554,
    longitude: 80.9412,
    location_name: 'Hazratganj Station Base',
    capability: 'Advanced Life Support / Ventilator / Cardiac Defib',
    crew_size: 3,
    fuel_percent: 92,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-02',
    callsign: 'ALS-MEDIC-02',
    name: 'ALS Ambulance Unit #02',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8641,
    longitude: 80.9995,
    location_name: 'Gomti Nagar Station Base',
    capability: 'Advanced Cardiac & Trauma Triage Unit',
    crew_size: 3,
    fuel_percent: 88,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-03',
    callsign: 'ALS-MEDIC-03',
    name: 'ALS Ambulance Unit #03',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8715,
    longitude: 80.9122,
    location_name: 'Chowk KGMU Sector Base',
    capability: 'Level-1 Polytrauma Mobile ICU',
    crew_size: 3,
    fuel_percent: 78,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-04',
    callsign: 'ALS-MEDIC-04',
    name: 'Ambulance Unit #04 (Critical Response)',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8588,
    longitude: 81.0042,
    location_name: 'Gomti Nagar Extension Base',
    capability: 'Mobile Intensive Care / Neonatal & Adult Life Support',
    crew_size: 4,
    fuel_percent: 95,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-05',
    callsign: 'BLS-MEDIC-05',
    name: 'BLS Ambulance Unit #05',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    latitude: 26.8295,
    longitude: 80.9234,
    location_name: 'Charbagh Rail Junction',
    capability: 'Basic Life Support / Mass Transit Extrication',
    crew_size: 2,
    fuel_percent: 64,
    current_incident_id: 'inc-1044',
    eta_minutes: 5,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-06',
    callsign: 'ALS-MEDIC-06',
    name: 'ALS Ambulance Unit #06',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8845,
    longitude: 80.9615,
    location_name: 'Indira Nagar Sector 14 Base',
    capability: 'Mobile Resuscitation & Oxygen Surge Unit',
    crew_size: 3,
    fuel_percent: 84,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-07',
    callsign: 'ALS-MEDIC-07',
    name: 'ALS Ambulance Unit #07',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8012,
    longitude: 80.8984,
    location_name: 'Kanpur Road Transport Base',
    capability: 'Highway Polytrauma Extrication Unit',
    crew_size: 3,
    fuel_percent: 90,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-08',
    callsign: 'BLS-MEDIC-08',
    name: 'BLS Ambulance Unit #08',
    type: 'AMBULANCE',
    status: 'BUSY',
    latitude: 26.8421,
    longitude: 80.9388,
    location_name: 'Kaiserbagh Bus Terminal',
    capability: 'Patient Transport & Oxygen Support',
    crew_size: 2,
    fuel_percent: 52,
    current_incident_id: 'inc-1049',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-09',
    callsign: 'ALS-MEDIC-09',
    name: 'ALS Ambulance Unit #09',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.7654,
    longitude: 80.9892,
    location_name: 'Shaheed Path Amar Base',
    capability: 'Critical Pediatric & Adult Life Support',
    crew_size: 3,
    fuel_percent: 96,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-10',
    callsign: 'BLS-MEDIC-10',
    name: 'BLS Ambulance Unit #10',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8892,
    longitude: 80.8645,
    location_name: 'Dubagga Hardoi Road Base',
    capability: 'Rapid Transit Medical Evacuation',
    crew_size: 2,
    fuel_percent: 81,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-11',
    callsign: 'ALS-MEDIC-11',
    name: 'ALS Ambulance Unit #11',
    type: 'AMBULANCE',
    status: 'MAINTENANCE',
    latitude: 26.8415,
    longitude: 80.9568,
    location_name: 'Central Command Depot',
    capability: 'Heavy Extrication Trauma Unit',
    crew_size: 0,
    fuel_percent: 40,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-amb-12',
    callsign: 'ALS-MEDIC-12',
    name: 'ALS Ambulance Unit #12',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    latitude: 26.8762,
    longitude: 80.9441,
    location_name: 'Mahanagar North Base',
    capability: 'Advanced Cardiac & Burn Care Unit',
    crew_size: 3,
    fuel_percent: 89,
    updated_at: new Date().toISOString(),
  },

  // 8 Fire Trucks
  {
    id: 'res-fire-01',
    callsign: 'HAZMAT-FIRE-01',
    name: 'Fire & Rescue Engine #01 (Hazmat)',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.8512,
    longitude: 80.9424,
    location_name: 'Hazratganj Main Fire Station',
    capability: 'Chemical foam / Heavy Water Tender / Thermal Imaging',
    crew_size: 6,
    fuel_percent: 94,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-02',
    callsign: 'LADDER-FIRE-02',
    name: 'Hydraulic Platform Fire Engine #02',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.8595,
    longitude: 81.0084,
    location_name: 'Gomti Nagar Fire Station',
    capability: '54m Hydraulic Aerial Ladder / Structural Collapse Rescue',
    crew_size: 5,
    fuel_percent: 91,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-03',
    callsign: 'HEAVY-FIRE-03',
    name: 'Heavy Foam Tender Fire Truck #03',
    type: 'FIRE_TRUCK',
    status: 'DISPATCHED',
    latitude: 26.8492,
    longitude: 80.9482,
    location_name: 'Hazratganj Commercial Plaza',
    capability: '12,000L Foam Deluge / Industrial Extinguishers',
    crew_size: 6,
    fuel_percent: 75,
    current_incident_id: 'inc-1043',
    eta_minutes: 3,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-04',
    callsign: 'RESCUE-FIRE-04',
    name: 'Urban Search & Rescue Tender #04',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.8672,
    longitude: 80.9168,
    location_name: 'Chowk Old City Station',
    capability: 'Concrete Cutters / Hydraulic Spreader / Acoustic Listeners',
    crew_size: 6,
    fuel_percent: 87,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-05',
    callsign: 'TENDER-FIRE-05',
    name: 'Rapid Response Fire Tender #05',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.8124,
    longitude: 80.9112,
    location_name: 'Alambagh Fire Substation',
    capability: 'High-Pressure Water Mist / Compressed Air Foam',
    crew_size: 4,
    fuel_percent: 92,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-06',
    callsign: 'WATER-FIRE-06',
    name: 'Water Bowzer Heavy Engine #06',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.8812,
    longitude: 80.9592,
    location_name: 'Indira Nagar Fire Post',
    capability: '15,000L Auxiliary Water Reservoir Pump',
    crew_size: 4,
    fuel_percent: 85,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-07',
    callsign: 'HEAVY-FIRE-07',
    name: 'Industrial Crash Tender #07',
    type: 'FIRE_TRUCK',
    status: 'AVAILABLE',
    latitude: 26.7892,
    longitude: 80.8845,
    location_name: 'Amausi Logistics Sector',
    capability: 'Aviation & Tanker Fire Suppression System',
    crew_size: 5,
    fuel_percent: 98,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-fire-08',
    callsign: 'RESCUE-FIRE-08',
    name: 'Disaster Extrication Fire Truck #08',
    type: 'FIRE_TRUCK',
    status: 'MAINTENANCE',
    latitude: 26.8392,
    longitude: 80.9512,
    location_name: 'Fire Department Central Workshop',
    capability: 'Heavy Winch / Pneumatic Lifting Bags',
    crew_size: 0,
    fuel_percent: 30,
    updated_at: new Date().toISOString(),
  },

  // 5 Rescue Boats (NDRF & SDRF Marine Units)
  {
    id: 'res-boat-01',
    callsign: 'NDRF-BOAT-01',
    name: 'NDRF Flood Rescue Boat #01',
    type: 'RESCUE_BOAT',
    status: 'AVAILABLE',
    latitude: 26.8582,
    longitude: 80.9785,
    location_name: 'Gomti Riverfront Pier 1',
    capability: 'Rigid Inflatable Boat / 14-Victim Capacity / Sonar Locator',
    crew_size: 4,
    fuel_percent: 95,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-boat-02',
    callsign: 'NDRF-BOAT-02',
    name: 'Rescue Boat #02 (High-Power Inflatable)',
    type: 'RESCUE_BOAT',
    status: 'AVAILABLE',
    latitude: 26.8632,
    longitude: 80.9982,
    location_name: 'Gomti Nagar Barrage Jetty',
    capability: '40HP Outboard Engine / Shallow Draft / Swiftwater Rescue',
    crew_size: 4,
    fuel_percent: 98,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-boat-03',
    callsign: 'SDRF-BOAT-03',
    name: 'SDRF Deepwater Rescue Craft #03',
    type: 'RESCUE_BOAT',
    status: 'AVAILABLE',
    latitude: 26.8712,
    longitude: 80.9254,
    location_name: 'Kudiyaghat Boat Landing',
    capability: 'Deep Diver Deployment / Night Searchlights',
    crew_size: 4,
    fuel_percent: 88,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-boat-04',
    callsign: 'NDRF-BOAT-04',
    name: 'NDRF Inflatable Assault Rescue Boat #04',
    type: 'RESCUE_BOAT',
    status: 'AVAILABLE',
    latitude: 26.8495,
    longitude: 81.0185,
    location_name: 'Janeshwar Mishra Lake Depot',
    capability: 'Submerged Debris Navigation / 10-Victim Floatation',
    crew_size: 3,
    fuel_percent: 92,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-boat-05',
    callsign: 'SDRF-BOAT-05',
    name: 'SDRF Multi-Role Rescue Skiff #05',
    type: 'RESCUE_BOAT',
    status: 'OFFLINE',
    latitude: 26.8398,
    longitude: 80.9741,
    location_name: 'Pipraghat Reserve Base',
    capability: 'Swiftwater Evacuation Skiff',
    crew_size: 0,
    fuel_percent: 45,
    updated_at: new Date().toISOString(),
  },

  // 8 Police Units
  {
    id: 'res-pol-01',
    callsign: 'LKO-PCR-01',
    name: 'Police Tactical Patrol Unit #01',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8488,
    longitude: 80.9452,
    location_name: 'Hazratganj Chauraha',
    capability: 'Crowd Control / Traffic Cordon / Drone Recon',
    crew_size: 3,
    fuel_percent: 88,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-02',
    callsign: 'LKO-PCR-02',
    name: 'Police Quick Response Team #02',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8572,
    longitude: 81.0035,
    location_name: 'Gomti Nagar Patrakarpuram',
    capability: 'High-Intensity Area Perimeter / Emergency Evac Escort',
    crew_size: 4,
    fuel_percent: 94,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-03',
    callsign: 'LKO-PCR-03',
    name: 'Police Patrol Unit #03',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8285,
    longitude: 80.9241,
    location_name: 'Charbagh Railway Station Gate 1',
    capability: 'Transit Perimeter Control / Megaphone Evacuation',
    crew_size: 3,
    fuel_percent: 79,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-04',
    callsign: 'LKO-PCR-04',
    name: 'Highway Patrol Interceptor #04',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.7782,
    longitude: 80.9854,
    location_name: 'Shaheed Path Outer Junction',
    capability: 'High-Speed Highway Escort / Flare Cordoning',
    crew_size: 2,
    fuel_percent: 91,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-05',
    callsign: 'LKO-PCR-05',
    name: 'Old City Police Mobile #05',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8695,
    longitude: 80.9135,
    location_name: 'Chowk Kotwali Post',
    capability: 'Narrow Alley Access / Public Order',
    crew_size: 3,
    fuel_percent: 85,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-06',
    callsign: 'LKO-PCR-06',
    name: 'Police Command Mobile #06',
    type: 'POLICE_UNIT',
    status: 'DISPATCHED',
    latitude: 26.8492,
    longitude: 80.9478,
    location_name: 'Hazratganj Commercial Plaza',
    capability: 'Mobile Incident Command / Radio Repeater',
    crew_size: 4,
    fuel_percent: 72,
    current_incident_id: 'inc-1043',
    eta_minutes: 2,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-07',
    callsign: 'LKO-PCR-07',
    name: 'Police Flying Squad #07',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8824,
    longitude: 80.9578,
    location_name: 'Indira Nagar Kaleva Chauraha',
    capability: 'Rapid Response / Traffic Clearance',
    crew_size: 3,
    fuel_percent: 83,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-pol-08',
    callsign: 'LKO-PCR-08',
    name: 'Police PCR Unit #08',
    type: 'POLICE_UNIT',
    status: 'AVAILABLE',
    latitude: 26.8115,
    longitude: 80.9095,
    location_name: 'Alambagh Chauraha',
    capability: 'General Patrol & Evac Guidance',
    crew_size: 2,
    fuel_percent: 90,
    updated_at: new Date().toISOString(),
  },

  // 10 Medical Teams (Doctors & Disaster Paramedics)
  {
    id: 'res-med-01',
    callsign: 'RAPID-MED-01',
    name: 'KGMU Field Triage Medical Team #01',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8682,
    longitude: 80.9148,
    location_name: 'KGMU Trauma Center Deck',
    capability: 'Surgical Triage / Mass Casualty Life Support / Thoracic Care',
    crew_size: 5,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-02',
    callsign: 'RAPID-MED-02',
    name: 'RMLIMS Disaster Medical Squad #02',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8618,
    longitude: 81.0022,
    location_name: 'RMLIMS Emergency Deck',
    capability: 'Severe Hemorrhage Control / Orthopedic Splinting / Crush Syndrome Care',
    crew_size: 5,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-03',
    callsign: 'RAPID-MED-03',
    name: 'Sahara Rapid Trauma Team #03',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8532,
    longitude: 81.0118,
    location_name: 'Sahara Hospital Deck',
    capability: 'Cardiac Resuscitation / Burn Dressing / Mobile Blood Unit',
    crew_size: 4,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-04',
    callsign: 'RAPID-MED-04',
    name: 'Civil Hospital Field Medical Team #04',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8482,
    longitude: 80.9472,
    location_name: 'Civil Hospital Park Rd',
    capability: 'Emergency First-Line Decontamination / Shock Treatment',
    crew_size: 4,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-05',
    callsign: 'RAPID-MED-05',
    name: 'SGPGI Critical Disaster Squad #05',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.7462,
    longitude: 80.9395,
    location_name: 'SGPGI Emergency Ward',
    capability: 'Advanced Toxicology / Blast Trauma Triage / Field Surgery',
    crew_size: 6,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-06',
    callsign: 'RAPID-MED-06',
    name: 'Balrampur Emergency Medical Team #06',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8578,
    longitude: 80.9242,
    location_name: 'Balrampur Hospital Ward',
    capability: 'Burn Care / Wound Debridement / Anti-Venom & Tetanus Triage',
    crew_size: 4,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-07',
    callsign: 'RAPID-MED-07',
    name: 'Apollo Medics Trauma Team #07',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.7918,
    longitude: 80.8928,
    location_name: 'Apollo Medics Deck',
    capability: 'Polytrauma Stabilization / Arterial Line Placement',
    crew_size: 5,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-08',
    callsign: 'RAPID-MED-08',
    name: 'Command Hospital Combat Medical Unit #08',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8218,
    longitude: 80.9578,
    location_name: 'Military Hospital Base',
    capability: 'Tactical Casualty Combat Care / Severe Crush Rescue',
    crew_size: 6,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-09',
    callsign: 'RAPID-MED-09',
    name: 'Medanta Emergency Trauma Squad #09',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.7728,
    longitude: 80.9988,
    location_name: 'Medanta Golf City Deck',
    capability: 'Pediatric & Adult Advanced Life Support',
    crew_size: 5,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'res-med-10',
    callsign: 'RAPID-MED-10',
    name: 'Vivekananda Emergency Care Unit #10',
    type: 'MEDICAL_TEAM',
    status: 'AVAILABLE',
    latitude: 26.8745,
    longitude: 80.9398,
    location_name: 'Vivekananda Institute Base',
    capability: 'Hypothermia & Water Ingestion Triage / Resuscitation',
    crew_size: 4,
    fuel_percent: 100,
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  // 1. CRITICAL: Gomti Nagar Flash Flood (Primary Demo Scenario)
  {
    id: 'inc-1042',
    incident_code: 'INC-1042',
    title: 'Flash Flood & Embankment Breach Emergency',
    description: 'Sudden breach in Gomti river diversion wall. Rapidly rising water has submerged ground floors of residential blocks. 18 people including 4 elderly and 2 children are trapped on second-floor balconies and rooftops with fast currents.',
    type: 'FLOOD',
    severity: 'CRITICAL',
    severity_score: 95,
    ai_confidence: 0.96,
    status: 'AWAITING_DISPATCH',
    latitude: 26.8568,
    longitude: 81.0078,
    location_name: 'Viram Khand 3, Gomti Nagar, Lucknow',
    people_affected: 34,
    people_injured: 4,
    people_trapped: 18,
    reported_by: 'Citizen Emergency Call & Local Police Patrol',
    reports_count: 5,
    reports: [
      {
        id: 'rep-1042-1',
        incident_id: 'inc-1042',
        source: 'CITIZEN',
        reporter_name: 'Aditya Srivastava',
        reporter_phone: '+91-9876543210',
        description: 'Water has crossed 6 feet near Viram Khand park. 18 people trapped on rooftops, power lines submerged, urgent boat needed!',
        latitude: 26.8569,
        longitude: 81.0079,
        timestamp: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
      },
      {
        id: 'rep-1042-2',
        incident_id: 'inc-1042',
        source: 'POLICE',
        reporter_name: 'PCR-02 Sub-Inspector',
        description: 'Confirmed severe inundation across 4 residential lanes. Current velocity approx 3.5 m/s. Watercraft deployment mandatory.',
        latitude: 26.8566,
        longitude: 81.0075,
        timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      },
      {
        id: 'rep-1042-3',
        incident_id: 'inc-1042',
        source: 'SENSOR',
        description: 'Smart Flow Sensor GOMTI-SF-09 reports water level surge +2.8m above safety threshold in 20 minutes.',
        latitude: 26.8570,
        longitude: 81.0080,
        timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
    ],
    ai_analysis: {
      incident_type: 'FLOOD',
      severity: 'CRITICAL',
      severity_score: 95,
      confidence: 0.96,
      people_affected: 34,
      people_injured: 4,
      people_trapped: 18,
      resources_required: [
        { type: 'RESCUE_BOAT', quantity: 2, reason: 'Swift water navigation and rooftop extraction of 18 trapped citizens' },
        { type: 'AMBULANCE', quantity: 2, reason: 'Hypothermia and water ingestion trauma triage' },
        { type: 'MEDICAL_TEAM', quantity: 1, reason: 'On-site immediate resuscitation and triage' },
        { type: 'POLICE_UNIT', quantity: 1, reason: 'Perimeter cordon and public safety' },
      ],
      reasoning: [
        '18 citizens trapped with water levels rapidly rising above first floor balconies.',
        'High water flow velocity creates imminent structural erosion hazard.',
        'Dense residential population requires immediate high-capacity motorized rescue craft.',
        'Nearest critical trauma hospital Dr. Ram Manohar Lohia Institute (RMLIMS) has 12 emergency beds available.',
      ],
      immediate_hazards: ['Submerged high-voltage electric distribution cables', 'Swiftwater current ~3.5 m/s', 'Hypothermia'],
      secondary_risks: ['Foundation undermining of adjacent brick structures', 'Sewage contamination in drinking supply'],
      recommended_hospital_specialty: 'Emergency Trauma & Critical Hypothermia / Drowning Care (RMLIMS)',
      generated_at: new Date().toISOString(),
    },
    created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },

  // 2. CRITICAL: Commercial Complex 4-Alarm Fire (Hazratganj)
  {
    id: 'inc-1043',
    incident_code: 'INC-1043',
    title: '4-Alarm Commercial Complex Fire & Smoke Trap',
    description: 'Major fire broke out in basement electronics godown, dense toxic smoke has engulfed the central atrium. Multiple office workers trapped on 3rd and 4th floors.',
    type: 'FIRE',
    severity: 'CRITICAL',
    severity_score: 92,
    ai_confidence: 0.94,
    status: 'DISPATCHED',
    latitude: 26.8492,
    longitude: 80.9478,
    location_name: 'Hazratganj Multi-Story Plaza, MG Marg, Lucknow',
    people_affected: 45,
    people_injured: 6,
    people_trapped: 11,
    reported_by: 'Building Management & Automated Heat Alarm',
    reports_count: 4,
    ai_analysis: {
      incident_type: 'FIRE',
      severity: 'CRITICAL',
      severity_score: 92,
      confidence: 0.94,
      people_affected: 45,
      people_injured: 6,
      people_trapped: 11,
      resources_required: [
        { type: 'FIRE_TRUCK', quantity: 2, reason: 'Hydraulic ladder for 4th floor rescue and foam deluge' },
        { type: 'AMBULANCE', quantity: 2, reason: 'Smoke inhalation and severe burn treatment' },
        { type: 'POLICE_UNIT', quantity: 1, reason: 'MG Marg traffic diversion' },
      ],
      reasoning: [
        'Active toxic cyanide/plastic smoke propagation via central HVAC ducts.',
        '11 persons awaiting aerial ladder rescue from upper windows.',
        'High heat gradient risking flashover to adjacent retail wings.',
      ],
      immediate_hazards: ['Toxic smoke asphyxiation', 'Flashover explosion', 'Structural glass breakage'],
      recommended_hospital_specialty: 'Level-1 Burn Care & Hyperbaric Oxygen (Civil Hospital / KGMU)',
      generated_at: new Date().toISOString(),
    },
    dispatches: [
      {
        id: 'disp-1043-1',
        incident_id: 'inc-1043',
        resource_id: 'res-fire-03',
        hospital_id: 'hosp-06',
        assigned_by: 'Inspector Vikram Rathore',
        ai_recommended: true,
        eta_minutes: 3,
        status: 'RESPONDING',
        assigned_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
      {
        id: 'disp-1043-2',
        incident_id: 'inc-1043',
        resource_id: 'res-pol-06',
        assigned_by: 'Inspector Vikram Rathore',
        ai_recommended: true,
        eta_minutes: 2,
        status: 'RESPONDING',
        assigned_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },

  // 3. CRITICAL: Outer Ring Road Multi-Vehicle Tanker Pileup
  {
    id: 'inc-1044',
    incident_code: 'INC-1044',
    title: 'Multi-Vehicle Tanker Collision & Hazardous Fuel Spill',
    description: 'High-speed collision between diesel tanker, passenger bus, and two cars on Shaheed Path express bypass. Massive fuel spill with risk of ignition. Multiple passengers pinned.',
    type: 'ROAD_ACCIDENT',
    severity: 'CRITICAL',
    severity_score: 89,
    ai_confidence: 0.93,
    status: 'DISPATCHED',
    latitude: 26.7824,
    longitude: 80.9912,
    location_name: 'Amar Shaheed Path KM 14, Near Golf City Exit, Lucknow',
    people_affected: 28,
    people_injured: 8,
    people_trapped: 3,
    reported_by: 'Highway Surveillance Camera & NHAI Patrol',
    reports_count: 6,
    ai_analysis: {
      incident_type: 'ROAD_ACCIDENT',
      severity: 'CRITICAL',
      severity_score: 89,
      confidence: 0.93,
      people_affected: 28,
      people_injured: 8,
      people_trapped: 3,
      resources_required: [
        { type: 'AMBULANCE', quantity: 3, reason: 'Polytrauma transfer for 8 injured victims' },
        { type: 'FIRE_TRUCK', quantity: 1, reason: 'Hydrocarbon foam blanket over 4,000L fuel spill' },
        { type: 'POLICE_UNIT', quantity: 2, reason: 'Total highway roadblock and secondary crash prevention' },
      ],
      reasoning: [
        'Volatile flammable diesel vapor cloud over active expressway.',
        'Extrication jaws required for 3 crushed vehicle occupants.',
        'Medanta Super Specialty and SGPGI within 8 minutes for rapid trauma reception.',
      ],
      immediate_hazards: ['Ignition of fuel puddle', 'Highway secondary collisions', 'Severe hemorrhagic shock'],
      recommended_hospital_specialty: 'Medanta Polytrauma & Surgical Resuscitation',
      generated_at: new Date().toISOString(),
    },
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  },

  // 4. HIGH: Building Structural Collapse (Old City)
  {
    id: 'inc-1045',
    incident_code: 'INC-1045',
    title: 'Heritage Building Roof & Balcony Collapse',
    description: 'Portion of a three-story old brick masonry building in Chowk collapsed following foundation water seepage. Debris fell onto crowded bazaar alley.',
    type: 'BUILDING_COLLAPSE',
    severity: 'HIGH',
    severity_score: 78,
    ai_confidence: 0.91,
    status: 'VERIFIED',
    latitude: 26.8674,
    longitude: 80.9152,
    location_name: 'Chowk Bazaar Near Victoria Street, Lucknow',
    people_affected: 16,
    people_injured: 5,
    people_trapped: 2,
    reported_by: 'Shopkeeper Association & Police PCR-05',
    reports_count: 3,
    ai_analysis: {
      incident_type: 'BUILDING_COLLAPSE',
      severity: 'HIGH',
      severity_score: 78,
      confidence: 0.91,
      people_affected: 16,
      people_injured: 5,
      people_trapped: 2,
      resources_required: [
        { type: 'FIRE_TRUCK', quantity: 1, reason: 'Hydraulic search & extrication tender' },
        { type: 'AMBULANCE', quantity: 2, reason: 'Crush injury stabilization' },
        { type: 'MEDICAL_TEAM', quantity: 1, reason: 'Field triage at Chowk' },
      ],
      reasoning: [
        'Fragile adjacent structures at risk of secondary collapse.',
        'Debris blocking narrow 12-foot lane preventing standard vehicle access.',
      ],
      immediate_hazards: ['Falling brickwork', 'Crush syndrome', 'Narrow access route'],
      recommended_hospital_specialty: 'KGMU Trauma Center (500m away)',
      generated_at: new Date().toISOString(),
    },
    created_at: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },

  // 5. HIGH: Charbagh Rail Yard Ammonia / Chemical Leak
  {
    id: 'inc-1046',
    incident_code: 'INC-1046',
    title: 'Freight Train Chemical Cylinder Valve Leak',
    description: 'Pungent vapor leak detected from stationary industrial refrigeration wagon near Platform 7 rail yard. Eye burning and respiratory distress reported by 14 railway staff.',
    type: 'HAZMAT',
    severity: 'HIGH',
    severity_score: 74,
    ai_confidence: 0.92,
    status: 'AWAITING_DISPATCH',
    latitude: 26.8312,
    longitude: 80.9221,
    location_name: 'Charbagh Railway Freight Marshalling Yard, Lucknow',
    people_affected: 22,
    people_injured: 6,
    people_trapped: 0,
    reported_by: 'Station Master & Railway Protection Force',
    reports_count: 4,
    ai_analysis: {
      incident_type: 'HAZMAT',
      severity: 'HIGH',
      severity_score: 74,
      confidence: 0.92,
      people_affected: 22,
      people_injured: 6,
      people_trapped: 0,
      resources_required: [
        { type: 'FIRE_TRUCK', quantity: 1, reason: 'Hazmat chemical suit team and water curtain neutralization' },
        { type: 'AMBULANCE', quantity: 2, reason: 'Oxygen delivery for bronchospasm patients' },
        { type: 'POLICE_UNIT', quantity: 1, reason: '500m downwind evacuation perimeter' },
      ],
      reasoning: [
        'Ammonia gas dispersion drifting towards passenger waiting concourse.',
        'Rapid water fog scrubbing required to prevent broad exposure.',
      ],
      immediate_hazards: ['Corrosive respiratory irritation', 'Explosive gas mixture in enclosed spaces'],
      recommended_hospital_specialty: 'Balrampur Hospital Toxic Inhalation Ward',
      generated_at: new Date().toISOString(),
    },
    created_at: new Date(Date.now() - 41 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },

  // 6. HIGH: Outer Siphon Water Channel Overflow
  {
    id: 'inc-1047',
    incident_code: 'INC-1047',
    title: 'Canal Siphon Overflow Threatening Slum Dwellings',
    description: 'Sharda canal distributary overflowed at Haider Canal culvert. Water has entered 30 low-lying informal settlements. Evacuation assistance required for 60+ individuals.',
    type: 'FLOOD',
    severity: 'HIGH',
    severity_score: 71,
    ai_confidence: 0.89,
    status: 'VERIFIED',
    latitude: 26.8385,
    longitude: 80.9324,
    location_name: 'Haider Canal Culvert, Kaiserbagh South, Lucknow',
    people_affected: 64,
    people_injured: 2,
    people_trapped: 0,
    reported_by: 'Municipal Ward Councilor & Citizen Helpline',
    reports_count: 3,
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },

  // 7. HIGH: Industrial Boiler Pressure Explosion
  {
    id: 'inc-1048',
    incident_code: 'INC-1048',
    title: 'Food Processing Plant Boiler Rupture',
    description: 'High-pressure steam boiler ruptured at an agro-processing unit. 4 workers sustained serious steam scald burns and blast trauma.',
    type: 'FIRE',
    severity: 'HIGH',
    severity_score: 68,
    ai_confidence: 0.90,
    status: 'DISPATCHED',
    latitude: 26.7645,
    longitude: 80.8712,
    location_name: 'Nadarganj Industrial Estate, Amausi, Lucknow',
    people_affected: 12,
    people_injured: 4,
    people_trapped: 0,
    reported_by: 'Factory Safety Officer',
    reports_count: 2,
    created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },

  // 8. HIGH: Alambagh Metro Junction Multi-Car Crash
  {
    id: 'inc-1049',
    incident_code: 'INC-1049',
    title: 'Metro Pillar 82 Major Intersection Collision',
    description: 'DTC luxury sleeper bus struck metro support pillar after brake failure, colliding with auto rickshaw and two motorbikes.',
    type: 'ROAD_ACCIDENT',
    severity: 'HIGH',
    severity_score: 66,
    ai_confidence: 0.92,
    status: 'RESPONDING',
    latitude: 26.8145,
    longitude: 80.9082,
    location_name: 'Alambagh Metro Pillar 82, Kanpur Rd, Lucknow',
    people_affected: 18,
    people_injured: 7,
    people_trapped: 1,
    reported_by: 'Metro Security Patrol',
    reports_count: 5,
    created_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },

  // 9. MEDIUM: Transformer Blast & Grid Local Outage
  {
    id: 'inc-1050',
    incident_code: 'INC-1050',
    title: '11KV Substation Transformer Oil Fire',
    description: 'Distribution transformer exploded with burning mineral oil spreading to adjacent tree canopy and roadside stalls.',
    type: 'FIRE',
    severity: 'MEDIUM',
    severity_score: 52,
    ai_confidence: 0.88,
    status: 'VERIFIED',
    latitude: 26.8824,
    longitude: 80.9634,
    location_name: 'Sector 14 Chauraha, Indira Nagar, Lucknow',
    people_affected: 8,
    people_injured: 1,
    people_trapped: 0,
    reported_by: 'UPPCL Power Grid Dispatch',
    reports_count: 2,
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },

  // 10. MEDIUM: Alambagh Sunday Market Crowd Crush
  {
    id: 'inc-1051',
    incident_code: 'INC-1051',
    title: 'Congested Market Panic & Minor Stampede',
    description: 'False short-circuit rumor triggered panic surge in narrow shopping arcade. Several elderly shoppers knocked down with minor fractures.',
    type: 'OTHER',
    severity: 'MEDIUM',
    severity_score: 48,
    ai_confidence: 0.87,
    status: 'VERIFIED',
    latitude: 26.8118,
    longitude: 80.9125,
    location_name: 'Alambagh Main Bazaar, Lucknow',
    people_affected: 15,
    people_injured: 5,
    people_trapped: 0,
    reported_by: 'Market Police Post',
    reports_count: 2,
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },

  // 11. MEDIUM: Construction Scaffold Collapse
  {
    id: 'inc-1052',
    incident_code: 'INC-1052',
    title: 'Commercial Tower Scaffolding Partial Failure',
    description: 'Heavy steel scaffolding collapsed on external facade from 5th floor level. 2 workers hanging on safety harnesses, street cordoned.',
    type: 'BUILDING_COLLAPSE',
    severity: 'MEDIUM',
    severity_score: 45,
    ai_confidence: 0.89,
    status: 'AWAITING_DISPATCH',
    latitude: 26.8784,
    longitude: 81.0215,
    location_name: 'Faizabad Road IT Park Zone, Lucknow',
    people_affected: 6,
    people_injured: 1,
    people_trapped: 2,
    reported_by: 'Project Site Manager',
    reports_count: 1,
    created_at: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },

  // 12. MEDIUM: School Bus Mechanical Breakdown in Flooded Underpass
  {
    id: 'inc-1053',
    incident_code: 'INC-1053',
    title: 'School Transport Bus Stalled in Waterlogged Underpass',
    description: 'Empty school transport bus engine submerged in 3-foot deep rainwater underpass. Driver and 2 attendants safe on roof.',
    type: 'ROAD_ACCIDENT',
    severity: 'LOW',
    severity_score: 28,
    ai_confidence: 0.95,
    status: 'RESOLVED',
    latitude: 26.8624,
    longitude: 80.9512,
    location_name: 'Nishatganj Railway Underpass, Lucknow',
    people_affected: 3,
    people_injured: 0,
    people_trapped: 0,
    reported_by: 'Traffic Control Room',
    reports_count: 1,
    created_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
];
